### ISSUE TITLE
Usage of Consistency::flexEntity breaks static analysis

### ISSUE THREAD

**Issue by shadowhand** [hoaproject/Consistency#29]
I am using [psalm](https://github.com/vimeo/psalm) for static analysis.

Because `flexEntity()` uses `class_alias()`, which is runtime only, static analysis cannot process it and flags it as an undefined class.

Example of problem: https://travis-ci.org/shadowhand/latitude/jobs/363503556#L613-L618

**Comment by vonglasow** [comment]
Hello, 

Yes, it's a problem related to static analysis and not for the usage. I don't really get your point, it's more related to [psalm](https://github.com/vimeo/psalm)

**Comment by Hywan** [comment]
Hi @shadowhand,

I don't know how to fix that. We use flex entities for backward and foreward compatibility. I know it sucks with static analysis.

You can use either `Hoa\Ruler\Ruler` (the fully-qualified class name), which should suppress the warning from Psalm I suppose, or use the `@psalm-suppress UndefinedClass` annotation. Does it work?

**Comment by shadowhand** [comment]
I am using `@psalm-suppress` for now.

In my opinion, a better solution would be define the actual flex entities instead of using `class_alias`:

```php
class Ruler extends Ruler\Ruler {}
```

More efficient and works properly with static analysis.

**Comment by Pierozi** [comment]
Hello @shadowhand 

We have a [cli command](https://github.com/hoaproject/Devtools#expandflexentities) to generate the stub of all entities if you need it.
you can run this before the static analysis tools.

**Comment by shadowhand** [comment]
So in order to support static analysis, I also need to install `hoa/console` and all it's dependencies? Not exactly ideal.

**Comment by Pierozi** [comment]
Sounds appropriate in `require-dev`.
You can still commit the stubs in your project if it suits you.

**Comment by shadowhand** [comment]
It works. I don't particularly like it, but it works.
